apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/name: prometheus-telegraf-custom
  name: prometheus-telegraf-custom
  namespace: newton
