apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/name: prometheus-telegraf-custom
  name: prometheus-telegraf-custom
  namespace: newton
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
      app.kubernetes.io/name: prometheus-telegraf-custom
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: telegraf
      labels:
        app.kubernetes.io/component: telegraf
        app.kubernetes.io/name: prometheus-telegraf-custom
    spec:
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
            defaultMode: 420
      containers:
        image: telegraf:1.22
        imagePullPolicy: IfNotPresent
        name: telegraf
        ports:
        # WARNING: This is open to everyone 
        - containerPort: 9126
          name: telegraf
        volumeMounts:
          - name: telegraf-config-volume
            readOnly: true
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
        resources:
          requests:
            cpu: 4m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError       
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      securityContext: {}
      serviceAccount: prometheus-telegraf-custom
      serviceAccountName: prometheus-telegraf-custom
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
