apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/name: prometheus-telegraf-custom
  name: prometheus-telegraf-custom
  namespace: newton #or netwon-idracs or newton-develop
spec:
  endpoints:
  - interval: 5s
    port: telegraf
    scheme: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: telegraf
      app.kubernetes.io/name: prometheus-telegraf-custom
