{
 "title": "telegraf",
 "description": "SNMP Telegraf Prometheus Dashboard to Monitor Dell Hosts with iDRAC",
 "tags": [
  "idrac",
  "telegraf",
  "snmp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "idrac_host",
    "label": "iDRAC Host",
    "query": {
     "query": "SHOW TAG VALUES FROM \"idrac-hosts\" WITH KEY=\"system-name\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "iDRAC Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AVG CPU Temp",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "expr": "(avg_over_time(idrac_hosts_cpu2_temp[5m]) + avg_over_time(idrac_hosts_cpu1_temp[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "CPU 2 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu2-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CMOS Battery",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "sum_over_time(idrac_hosts_power_state[5m])",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cmos-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status Map",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[tag_system-name]]",
     "expr": "avg(idrac_hosts_system_globalstatus) by (system_model)",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "# of iDRACs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(idrac_hosts_system_globalstatus)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "query": "show tag values cardinality from \"idrac-hosts\" with key = \"system-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 15 },
   "repeat": "idrac_host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(idrac_hosts_system_uptime[5m])",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "idrac-url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "max(idrac_hosts_system_globalstatus)",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "count(sort(idrac_hosts_power_state{idrac_hosts_system_globalstatus=\"\"}))",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idrac_hosts_memory_status",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID Battery",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(idrac_hosts_system_uptime) by (system_servicetag)",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Intrusion",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "idrac_hosts_intrusion_sensor",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "OS Information",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 23 },
   "targets": [
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-osversion" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 23 },
   "repeat": "idrac_host",
   "targets": [
    {
     "alias": "Inlet Temp",
     "expr": "avg(idrac_hosts_exhaust_temp) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Exhaust Temp",
     "expr": "avg(idrac_hosts_temp_status) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "exhaust-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "avg(idrac_hosts_exhaust_temp) by (system_model)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(idrac_hosts_temp_status) by (system_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-severity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Watts",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "System Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Fan 1",
     "expr": "avg(idrac_hosts_fan1_speed) by (system_servicetag)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 2",
     "expr": "avg(idrac_hosts_fan1_speed) by (system_model)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan2-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 3",
     "expr": "avg(idrac_hosts_fan1_speed) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan3-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 4",
     "expr": "avg(idrac_hosts_fan2_speed) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan4-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 5",
     "expr": "avg(idrac_hosts_fan3_speed) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan5-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 6",
     "expr": "avg(idrac_hosts_fan4_speed) by (system_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan6-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "avg(idrac_hosts_fan3_speed) by (system_servicetag)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-vendor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-current_mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "$idrac_host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "idrac_host",
   "targets": [
    {}
   ]
  }
 ]
}