{
 "title": "Kepler Exporter Dashboard",
 "description": "Dashboard for Kepler Exporter",
 "tags": [
  "kepler",
  "energy consumption"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pod_energy_stat, pod_namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pod_energy_stat{pod_namespace=\"$namespace\"}, pod_name)"
    }
   },
   { "name": "coal", "query": "2.23" },
   { "name": "natural_gas", "query": "0.91" },
   { "name": "petroleum", "query": "2.13" }
  ]
 },
 "panels": [
  {
   "title": "Carbon Emissions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kepler Tests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "delta(sum(pod_curr_energy_millijoule{pod_namespace='$namespace'})[10m:])\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "predict_linear(sum(pod_curr_energy_millijoule{pod_namespace='$namespace'})[4h:], 3600)\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod_namespace) (sum_over_time(pod_curr_energy_in_pkg_millijoule[24h])*15/3/3600000000)\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "deriv(sum(pod_curr_energy_millijoule{pod_node_name='$pod',pod_namespace='$namespace'})[10m:])\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace Carbon Footprint (pounds per kWh in 24hrs)",
   "type": "bargauge",
   "description": "Using CO2 emissions  by power generation type as reported by US Energy Information Administration https://www.eia.gov/tools/faqs/faq.php?id=74&t=11",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pod_curr_energy_millijoule{pod_namespace='$namespace'}[24h])/(20*60*24)/3600000000*$coal)\n ",
     "legendFormat": "CO2 Coal"
    },
    {
     "expr": "sum(rate(pod_curr_energy_millijoule{pod_namespace='$namespace'}[24h])/(20*60*24)/3600000000*$petroleum)",
     "legendFormat": "CO2 Petroleum"
    },
    {
     "expr": "sum(rate(pod_curr_energy_millijoule{pod_namespace='$namespace'}[24h])/(20*60*24)/3600000000*$natural_gas)",
     "legendFormat": "CO2 Natural Gas"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Current Energy Consumption (mW)",
   "type": "timeseries",
   "description": "The mW per minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "CPU"
    },
    {
     "expr": "rate(pod_dram_energy_current{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[1m])/20",
     "legendFormat": "DRAM"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW) in 24hrs",
   "type": "timeseries",
   "description": "Total kW Consumed",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "TOTAL {{pod_name}}"
    },
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "CPU {{pod_name}}"
    },
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\", pod_name=\"$pod\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "DRAM {{pod_name}}"
    },
    { "legendFormat": "__auto" },
    {
     "expr": "sum by (pod_namespace) (sum_over_time(pod_curr_energy_in_pkg_millijoule[24h])*15/3/3600000000)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pod Energy Consumption (kW) in $namespace in 24hrs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pod_curr_energy_millijoule{pod_namespace=\"$namespace\"}[24h])/(20*60*24)/3600000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kW) by Namespace in 24hrs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod_namespace) (\n    rate(pod_curr_energy_millijoule[24h])/(20*60*24)/3600000000\n) "
    }
   ]
  }
 ]
}