apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf-metrics
  name: telegraf-exporter
  namespace: newton-idracs
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: telegraf-metrics
  sessionAffinity: None
  type: ClusterIP