--- 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: telegraf-metrics
  name: telegraf-metrics
  namespace: newton-idracs
spec:
  endpoints:
  - interval: 5s
    port: metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  selector:
    matchLabels:
      app: telegraf-metrics